apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: movereverses.kubemove.io
spec:
  group: kubemove.io
  names:
    kind: MoveReverse
    listKind: MoveReverseList
    plural: movereverses
    singular: movereverse
  scope: ""
  validation:
    openAPIV3Schema:
      description: MoveReverse is the Schema for the movereverses API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MoveReverseSpec defines the desired state of MoveReverse
          type: object
        status:
          description: MoveReverseStatus defines the observed state of MoveReverse
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
