apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: sample-es
spec:
  version: 7.5.2
  http:
    service:
      spec:
        type: NodePort
  nodeSets:
  - name: default
    count: 2
