apiVersion: kubemove.io/v1alpha1
kind: MoveEngine
metadata:
  name: sample-es-move
spec:
  movePair: demo-move-pair
  namespace: ns1
  remoteNamespace: ns2
  syncPeriod: "30 * * * *"
  plugin: elasticsearch-plugin
  selectors:
    matchLabels:
      name: sample-es
  includeResources: false
  mode: ${MODE}
  pluginParameters:
    repository:
      name: minio_repo
      type: s3
      bucket: demo
      prefix: es/backup
      endpoint: ${MINIO_SERVER_ADDRESS}
      scheme: http
      credentials: minio-credentials
    elasticsearch:
      serviceName: sample-es-es-http
      port: 9200
      namespace: default
      scheme: https
      authSecret: sample-es-es-elastic-user
      tlsSecret: sample-es-es-http-ca-internal
