apiVersion: v1
kind: ServiceAccount
metadata:
  name: eck-plugin
  labels:
    name: eck-plugin

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eck-plugin
  labels:
    name: eck-plugin
subjects:
- kind: ServiceAccount
  name: eck-plugin
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: eck-plugin
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: eck-plugin
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eck-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eck-plugin
  template:
    metadata:
      labels:
        name: eck-plugin
    spec:
      serviceAccountName: eck-plugin
      containers:
      - name: eck-plugin
        # Replace this with the built image name
        image: ${PLUGIN_IMAGE}
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVER
          value: "datasync.kubemove.svc,moveengine.kubemove.svc"
        - name: SERVER_PORT
          value: "9000,9000"
        - name: CLIENT
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: OPERATOR_NAME
          value: "kubemove"
