name: CI

on:
  push:
    branches-ignore:
    - 'release-*'
    tags-ignore:
    - '*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Setup Docker Registry
      env:
        REGISTRY: emruzhossain
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        USERNAME: emruzhossain
      run: |
        docker login --username ${USERNAME} --password ${DOCKER_TOKEN}

    - name: Run checks
      env:
        REGISTRY: emruzhossain
      run: |
        make lint

    - name: Build
      env:
        REGISTRY: emruzhossain
      run: |
        make build
